### ISSUE TITLE
how to get gc_bins_20000.pck and  nn_bins_20000.pck

### ISSUE THREAD

**Issue by meghavarshney** [marcelTBI/CNV_data#4]
HI can you please help . how to generate these files can you please clarify this as in mentioned step not able to find 
gc_bins_20000.pck 
nn_bins_20000.pck

**Comment by marcelTBI** [comment]
Hi, 
for hg19 reference, the files are pregenerated (in the data folder) and there is no need to regenerate them - they contain information on GC content per bin and the number of N (unknown) bases per bin. If you are interested in using this tool for other references, I highly recommend using it for hg19 and then liftover the regions to your reference of interest, since we did not test it for other references and you would need to adjust all the parameters.
